### ISSUE TITLE
This looks great

### ISSUE THREAD

**Issue by clozinski** [qntln/aiopubsub#1]
This looks like just what I am looking for.  A tree of pub/sub topics. 

Only I worry that it is out of date.  2016 is the last update.  Has much changed since then.  Does it work?  Would it be hard to make current?

When I look at the other packages.  ZeroMQ does a tree by characters.  Great for stock symbols.  MQTT really just does a list of strings, not a proper tree.  This seems to be the only one that really does trees. 

Are there any other packages I should consider?

**Comment by vitawasalreadytaken** [comment]
Hi @clozinski! We are using this heavily in our firm though we have been guilty of not updating the open source version here on GitHub. I am going to update it this week and let you know.

**Comment by PythonLinks** [comment]
I watched this, so I will be notified when updated.  I presume. 
I have been looking closely at MQTT, but they just have a string, not a data structure of names. 
So this is really much much better.  
I look forward to seeing what gets published.  Then I will have some more questions.

**Comment by vitawasalreadytaken** [comment]
@clozinski @PythonLinks So... this took me way more than a week and I am sorry. But aiopubsub==2.1.5 is out now. Please give it a shot and feel free to open issues if you run into any problems.

Note that even though subscription keys appear to form trees we don't represent them as such in the `Hub`. After much profiling we figured out it's fastest to keep a direct cache mapping published keys to subscribers. This is optimal in our use case where publisher keys and subscriptions change relatively infrequently.
